<?php return array (
  'custom-244' => 'detailed',
  'custom-245' => 'Who is JZB?',
  'custom-246' => 'Jiaozuo brake Co., Ltd. (abbreviated as JZB) is one of the most professional brake manufacturers in China with the largest scale, the most advanced equipment and the most complete inspection methods. Founded in 2002, covers an area of 126000 square meters, building area of 75000 square meters, fixed assets of 120 million yuan, more than 600 employees.',
  'custom-247' => 'How about our location?',
  'custom-248' => 'Jiaozuo brake Co., Ltd. is a manufacturer of brake research and development, production, sales and service. It is a well-known industrial brake manufacturer in the industry. The company is located in the north of Henan huaichuan plain - Jiaozuo, Zhengzhou and across the river, located in the Central Plains Economic Zone core area. It is Zhengzhou, Jiaozuo, Xinxiang, Luoyang, Jincheng five city radiation center, North and south is the material and cultural exchange, coal Sinotrans thoroughfare is the South Gate of Jiaozuo city. What are our business areas and market prospects?',
  'custom-249' => 'Company reports',
  'custom-250' => 'The company has more than 20 national patents, a number of national and trade associations issued certificates of honor, more than 300 professional and technical development team, more than 500 sets of testing CNC machining equipment. The early stage of the company is devoted to the R & D and design of brakes. The products are widely used in the fields of wind power generation, lifting transportation, metallurgy, mines, ports, terminals, petroleum, chemical, railway, water conservancy, construction machinery and so on. High quality products won the affirmation of new and old customers, and exported to Asia, Europe, the United States, Africa and other more than 20 countries and regions.',
  'custom-251' => 'At present, the company takes the development of new energy products as the leading direction, and forms a new development area with the development of wind power brakes and rail transportation products as the core. Advanced technical support, advanced equipment, perfect talent strategy and continuously optimized management system lay a solid foundation for the long-term development of the company. In addition, the company always adhere to the "customer as the center, and strive for the people" as the foundation, and constantly improve the corporate governance structure, organization, processes and assessment, so that the company maintained long-term growth.',
  'custom-252' => 'Service telephone',
  'custom-253' => 'category',
  'custom-254' => 'Talent sharing',
  'custom-255' => 'I want to share',
  'custom-256' => 'Perceived life',
  'custom-257' => 'Leben Passiert',
  'custom-258' => 'Welcome',
  'custom-259' => 'Member login',
  'custom-260' => 'Please enter your account number',
  'custom-261' => 'Please input a password',
  'custom-262' => 'Sign in',
  'custom-263' => 'Prompt',
  'custom-264' => 'Get your password and change your password',
  'custom-265' => 'Please contact the administrator',
  'custom-266' => 'Text Preview',
  'custom-267' => 'Hot Video',
  'custom-268' => 'You are not logged in. Please continue downloading after you login',
);